CREATE TABLE IF NOT EXISTS teams (
	team_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(5)
	);

CREATE TABLE IF NOT EXISTS players (
	player_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	team_ID INTEGER,
	name VARCHAR(40),
	FOREIGN KEY (team_ID) REFERENCES teams(team_ID)
	);

CREATE TABLE IF NOT EXISTS games (
	game_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	home_team VARCHAR(5),
	away_team VARCHAR(5),
	day DATE
	);

CREATE TABLE IF NOT EXISTS game_stats (
	game_ID INTEGER,
	player_ID INTEGER,
	stats INTEGER,
	FOREIGN KEY (game_ID) REFERENCES games(game_ID)
	FOREIGN KEY (player_ID) REFERENCES players(player_ID)
	);
