DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS game_stats;

CREATE TABLE IF NOT EXISTS teams (
	team_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(5)
	);

CREATE TABLE IF NOT EXISTS players (
	player_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	team_ID INT,
	name VARCHAR(40),
	FOREIGN KEY (team_ID) REFERENCES teams(team_ID)
	);

CREATE TABLE IF NOT EXISTS games (
	game_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	home_team VARCHAR(5),
	away_team VARCHAR(5),
	game_day DATE,
	home_won BOOLEAN
	);

CREATE TABLE IF NOT EXISTS game_stats (
	game_ID INT,
	player_ID INT,
	MP INT,
	FG INT,
	FGA INT,
	FGP INT,
	TPM INT,
	TPP INT,
	FT INT,
	FTA INT, 
	FTP INT,
	ORB INT,
	DRB INT,
	TRB INT, 
	AST INT, 
	STL INT, 
	BLK INT,
	TOV INT,
	PF INT,
	PTS INT,
	plusMINUS INT,
	FOREIGN KEY (game_ID) REFERENCES games(game_ID)
	FOREIGN KEY (player_ID) REFERENCES players(player_ID)
	);
